In [1]:
import numpy as np

In [19]:
A = np.array([[[1,1],[2,2],[3,3]],[[4,4],[5,5],[6,6]]])

In [20]:
A

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

In [21]:
A.ndim

3

In [22]:
A.shape

(2, 3, 2)

In [23]:
len(A),len(A[0]),len(A[0][0])

(2, 3, 2)

In [24]:
a0 = [[1,1],[2,2],[3,3]]
a1 = [[4,4],[5,5],[6,6]]

In [26]:
B = np.array([a0,a1])

In [27]:
B

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

In [29]:
A.shape==B.shape

True

In [36]:
B = np.array([[["a","a"],["b","b"],["c","c"]],[["d","d"],["e","e"],["f","f"]]])

In [37]:
C = np.concatenate([A,B],axis=0)
print(C)

[[['1' '1']
  ['2' '2']
  ['3' '3']]

 [['4' '4']
  ['5' '5']
  ['6' '6']]

 [['a' 'a']
  ['b' 'b']
  ['c' 'c']]

 [['d' 'd']
  ['e' 'e']
  ['f' 'f']]]


In [38]:
print(A.shape)
print(B.shape)
print(C.shape)

(2, 3, 2)
(2, 3, 2)
(4, 3, 2)


In [39]:
C = np.concatenate([A,B],axis=1)
print(C)
print(A.shape)
print(B.shape)
print(C.shape)

[[['1' '1']
  ['2' '2']
  ['3' '3']
  ['a' 'a']
  ['b' 'b']
  ['c' 'c']]

 [['4' '4']
  ['5' '5']
  ['6' '6']
  ['d' 'd']
  ['e' 'e']
  ['f' 'f']]]
(2, 3, 2)
(2, 3, 2)
(2, 6, 2)


In [41]:
C = np.concatenate([A,B],axis=2)
print(C)
print(A.shape)
print(B.shape)
print(C.shape)

[[['1' '1' 'a' 'a']
  ['2' '2' 'b' 'b']
  ['3' '3' 'c' 'c']]

 [['4' '4' 'd' 'd']
  ['5' '5' 'e' 'e']
  ['6' '6' 'f' 'f']]]
(2, 3, 2)
(2, 3, 2)
(2, 3, 4)


In [81]:
val = np.random.random([5,5])
print(val)

[[0.71353868 0.73283918 0.46853982 0.81884741 0.9980011 ]
 [0.49460614 0.68624875 0.58108437 0.30752397 0.87157827]
 [0.11879025 0.0894301  0.56669026 0.06961304 0.96290924]
 [0.15617033 0.34691365 0.93597255 0.37872761 0.67418537]
 [0.29170545 0.38047816 0.15926294 0.90178471 0.1996435 ]]


In [82]:
# Version A
conv = [(val<.25, "D"),
        ((.25<=val) & (val<.50), "C"),
        ((.50<=val) & (val<.75), "B"),
        (.75<=val, "A")]

In [83]:
res = np.empty(val.shape,dtype=str)

In [84]:
for cond, value in conv:
    res[cond] = value

In [85]:
res

array([['B', 'B', 'C', 'A', 'A'],
       ['C', 'B', 'B', 'C', 'A'],
       ['D', 'D', 'B', 'D', 'A'],
       ['D', 'C', 'A', 'C', 'B'],
       ['C', 'C', 'D', 'A', 'D']], dtype='<U1')

In [86]:
# Version B
conv = {x<.25 : "D",
       .25<=x<.50 : "C",
       .50<=x<.75 : "B",
       .75<=x : "A"}
def conversion(x):
    conv = {x<.25 : "D",
           .25<=x<.50 : "C",
           .50<=x<.75 : "B",
           .75<=x : "A"}
    return conv[True]

In [87]:
conversion_vectorized = np.vectorize(conversion)

In [88]:
conversion_vectorized

In [89]:
conversion_vectorized(val)

array([['B', 'B', 'C', 'A', 'A'],
       ['C', 'B', 'B', 'C', 'A'],
       ['D', 'D', 'B', 'D', 'A'],
       ['D', 'C', 'A', 'C', 'B'],
       ['C', 'C', 'D', 'A', 'D']], dtype='<U1')

In [90]:
conv_lambda_vec = np.vectorize(lambda x: {x<.25 : "D",
                                         .25<=x<.50 : "C",
                                         .50<=x<.75 : "B",
                                         .75<=x : "A"}[True])

In [91]:
conv_lambda_vec(val)

array([['B', 'B', 'C', 'A', 'A'],
       ['C', 'B', 'B', 'C', 'A'],
       ['D', 'D', 'B', 'D', 'A'],
       ['D', 'C', 'A', 'C', 'B'],
       ['C', 'C', 'D', 'A', 'D']], dtype='<U1')